spring:
    datasource:
        name: test
        #url: jdbc:mysql://localhost:3306/ag_business?useUnicode=true&characterEncoding=UTF8
        #username: root
        #password: root
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: cnmtcems
        password: cnmtcems
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: oracle.jdbc.OracleDriver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 1 from dual
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        database: 1
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest


logging:
    config: classpath:logback-boot.xml


eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
#        prefer-ip-address: true
#        ip-address: 192.168.0.166
    client:
        serviceUrl:
#           defaultZone: http://192.168.0.9:8761/eureka/
                    # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/