spring:
    datasource:
        name: test
#        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ag_admin?useUnicode=true&characterEncoding=UTF8
#        username: root
#        password: 123456
#        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: cnmtcems
        password: cnmtcems
        driver-class-name: oracle.jdbc.OracleDriver
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        database: 1
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

#redis-cache 相关
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: ${REDIS_HOST:localhost}
    port:  ${REDIS_PORT:6379}
    password:
    timeout: 2000
    # 服务或应用名
    sysName: ace-admin
    enable: true
    database: 0

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
        prefer-ip-address: true
        ip-address: 192.168.0.9
    client:
        serviceUrl:
#            defaultZone: http://192.168.0.9:8761/eureka/
             # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
             defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


logging:
    config: classpath:logback-boot.xml